keybinding:
  universal:
    quit: q
    return: <c-c>
    confirmInEditor: <enter>

customCommands:
  - key: "M"
    command: "git mergetool {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening git mergetool"
    subprocess: true
